spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8001/cognito/auth

hopeful-api:
  user-pool-id: userPoolId
  cognito-url: http://host.docker.internal:8001/cognito
  dynamo-db-url: http://host.docker.internal:8000
  frontend-url: http://localhost:3000
  matches-table-name: "matches"