spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_EWIfXTFmF

hopeful-api:
  user-pool-id: ${{secrets.userPoolId}}