spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001/cognito/auth

hopeful-api:
  user-pool-id: userPoolId
  client-id: clientId
  token-url: http://localhost:8001/cognito
  cognito-url: http://localhost:8001/cognito
  dynamo-db-url: http://localhost:8000
  frontend-url: http://localhost:3000
  matches-table-name: "matches"