spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <issuerUrl>

hopeful-api:
  user-pool-id: <userPoolId>
  client-id: <clientId>
  token-url: <tokenUrl>
  frontend-urls: [<frontendUrl>, <hubUrl>]
  matches-table-name: <matchesTableName>