name: Hopeful API Deploy

on:
  push:
    branches:
    - main
    
env:
  AWS_REGION: eu-west-1

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Run Maven Test
        run: mvn clean test

  build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Update issuerUrl
        run: sed -i 's#<issuerUrl>#${{ secrets.AWS_COGNITO_ISSUER_URL }}#' src/main/resources/application-production.yml

      - name: Update user pool ID
        run: sed -i 's/<userPoolId>/${{ secrets.AWS_COGNITO_USER_POOL_ID }}/' src/main/resources/application-production.yml

      - name: Update frontend URL
        run: sed -i 's#<frontendUrl>#"${{ secrets.FRONTEND_URL }}"#' src/main/resources/application-production.yml

      - name: Build with Maven
        run: mvn -B package -DskipTests -f pom.xml
      
      - name: Upload Maven Artifact
        uses: actions/upload-artifact@v3
        with:
          name: HopefulAPI_Artifacts
          path: target/HopefulAPI-0-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: HopefulAPI_Artifacts

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APP_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENV_NAME }}
          version_label: ${{github.run_number}}
          region: ${{env.AWS_REGION}}
          deployment_package: HopefulAPI-0-SNAPSHOT.jar

          
