name: Hopeful API Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Maven Test
        run: mvn clean test

  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Update issuerUrl
        run: sed -i 's#<issuerUrl>#${{ secrets.AWS_COGNITO_ISSUER_URL }}#' src/main/resources/application-production.yml

      - name: Update user pool ID
        run: sed -i 's/<userPoolId>/${{ secrets.AWS_COGNITO_USER_POOL_ID }}/' src/main/resources/application-production.yml

      - name: Update frontend URL
        run: sed -i 's#<frontendUrl>#"${{ secrets.FRONTEND_URL }}"#' src/main/resources/application-production.yml

      - name: Update Hub URL
        run: sed -i 's#<hubUrl>#"${{ secrets.HUB_URL }}"#' src/main/resources/application-production.yml

      - name: Update Matches table name
        run: sed -i 's#<matchesTableName>#"${{ secrets.MATCHES_TABLE_NAME }}"#' src/main/resources/application-production.yml

      - name: Update Client ID
        run: sed -i 's#<clientId>#"${{ secrets.AWS_COGNITO_CLIENT_ID }}"#' src/main/resources/application-production.yml

      - name: Update Token URL
        run: sed -i 's#<tokenUrl>#"${{ secrets.AWS_COGNITO_TOKEN_URL }}"#' src/main/resources/application-production.yml

      - name: Build with Maven
        run: mvn -B package -DskipTests -f pom.xml

      - name: Upload Maven Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: HopefulAPI_Artifacts
          path: target/HopefulAPI-${{github.run_id}}.jar

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: |
          aws s3 cp "target/HopefulAPI-${{github.run_id}}.jar" s3://elasticbeanstalk-eu-west-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/HopefulAPI/
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.AWS_EB_APP_NAME }} --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-eu-west-1-${{ secrets.AWS_ACCOUNT_ID }}}",S3Key="artifact/artifact/HopefulAPI/HopefulAPI-${{github.run_id}}.jar"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.AWS_EB_APP_NAME }} --environment-name ${{ secrets.AWS_EB_ENV_NAME }} --version-label ${{github.run_id}}
          aws elasticbeanstalk wait environment-updated --application-name ${{ secrets.AWS_EB_APP_NAME }} --environment-name ${{ secrets.AWS_EB_ENV_NAME }}